### PR TITLE
Add logback configuration files used by Tango java applications

### PR DESCRIPTION
**Pull request by beenje**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

I'm looking at packaging atk-panel and atk-tuning and noticed that those applications require a `logback.xml` configuration file for logging.
I think it makes sense to put those files in the `jtango` conda package as all java applications will have it as dependency.

I took those files from the TangoSourceDistribution.

The current package fails to install on Windows because $PREFIX/share/java doesn't exist.
This recipe can't be "noarch: generic". I removed that.

### CODE REVIEW

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
@bourtemb I'd appreciate your input on this.

**Review by bourtemb — APPROVED** [review]
It looks like you took the logback xml files from the Tango Source Distribution.  
The changes look OK for me, but I am no Java expert.

**Comment by bourtemb** [comment]
Maybe @gwen-soleil could confirm that these logback files are suitable for most of the users using JTango?

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
